version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-8395
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - geppettodevproject_8395-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-8395
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-8395
    container_name: authproxy-8395
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-8395
    container_name: securitymanager-8395
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-8395
    container_name: camundasvc-8395
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-8395
    container_name: apigateway-8395
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - student
      - college
      - place



  student: 
    build: ../../../application/services/custom_services/student
    image: student-8395
    container_name: student-8395
    ports: 
      - 8016:8016
    env_file: .env
    depends_on:
      - mongo

  college: 
    build: ../../../application/services/custom_services/college
    image: college-8395
    container_name: college-8395
    ports: 
      - 8017:8017
    env_file: .env
    depends_on:
      - mongo

  place: 
    build: ../../../application/services/custom_services/place
    image: place-8395
    container_name: place-8395
    ports: 
      - 8018:8018
    env_file: .env
    depends_on:
      - mongo


volumes:
  geppettodevproject_8395-volume:
    driver: local
